import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
      <>
        <Head>
          <title>LOGIN - TECBANK</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <div className="grid grid-rows-[11.13vh_1fr] h-screen w-screen">
              {/* Header */}
              <div className="bg-[#00072D] flex items-center px-4">
                  {/* Puedes agregar contenido dentro del header aquí */}
              </div>

              {/* Body */}
              <div className="flex justify-center items-center">
                  <div className="flex flex-col justify-around items-center w-[30.5vw] h-[60.44vh] bg-[#FAFAFF] shadow-lg rounded-lg sm:w-[80vw] sm:max-w-lg sm:h-auto sm:py-8 sm:px-6">
                      <div className="sm:mx-auto sm:w-full sm:max-w-sm">
                          <img className="mx-auto h-10 w-auto" src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company" />
                          <h2 className="mt-10 text-center text-2xl font-bold tracking-tight text-gray-900">Sign in to your account</h2>
                      </div>

                      <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
                          <form className="space-y-6" action="#" method="POST">
                              <div>
                                  <label htmlFor="email" className="block text-sm font-medium text-gray-900">Email address</label>
                                  <div className="mt-2">
                                      <input
                                          type="email"
                                          name="email"
                                          id="email"
                                          autoComplete="email"
                                          required
                                          className="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm"
                                      />
                                  </div>
                              </div>

                              <div>
                                  <div className="flex items-center justify-between">
                                      <label htmlFor="password" className="block text-sm font-medium text-gray-900">Password</label>
                                      <div className="text-sm">
                                          <a href="#" className="font-semibold text-[#1D264D] hover:text-[#7180AC]">Forgot password?</a>
                                      </div>
                                  </div>
                                  <div className="mt-2">
                                      <input
                                          type="password"
                                          name="password"
                                          id="password"
                                          autoComplete="current-password"
                                          required
                                          className="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm"
                                      />
                                  </div>
                              </div>

                              <div>
                                  <button
                                      type="submit"
                                      className="flex w-full justify-center rounded-md bg-[#170A1C] px-3 py-1.5 text-sm font-semibold text-white shadow-xs hover:bg-[#39446D] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                                  >
                                      Sign in
                                  </button>
                              </div>
                          </form>

                          <p className="mt-10 text-center text-sm text-gray-500">
                              Not a member?
                              <a href="#" className="font-semibold text-[#1D264D] hover:text-[#7180AC]">Start a 14-day free trial</a>
                          </p>
                      </div>
                  </div>
              </div>
          </div>

      </>
  );
}
