import Head from "next/head";
import Image from "next/image";
import { Nunito } from "next/font/google";
import styles from "@/styles/login.module.css";
import { Button, Container, Row, Col, Form } from 'react-bootstrap'; // Importa componentes de React-Bootstrap
import  "bootstrap/dist/css/bootstrap.min.css"
import {Flex,Box} from "@/components/layout"

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>LOGIN - TECBANK CLIENTES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      {/* Header */}
      <div className={styles.header}>
        <h2 className={styles.title_header}>TECBANK | PORTAL CLIENTES</h2>
      </div>
      
      {/* Body */}
      <div className={styles.body}>
        <div className={styles.formContainer}>
          <div className={styles.logoContainer}>
            <img
              className={styles.logo}
              src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=indigo&shade=600"
              alt="Your Company"
            />
            <h3 className={styles.title}>Inicio de sesión</h3>
          </div>
          
          <div className={styles.formContent}>
            <Form className={styles.form} action="#" method="POST">
              <div>
                <Form.Label htmlFor="username" className={styles.label}>Usuario</Form.Label>
                <div className={styles.inputWrapper}>
                  <Form.Control
                    type="text"
                    name="username"
                    id="username"
                    autoComplete="username"
                    required
                    className={styles.input}
                  />
                </div>
              </div>
              
              <div>
                <div className={styles.passwordWrapper}>
                  <Form.Label htmlFor="password" className={styles.label}>Contraseña</Form.Label>
                  <div className={styles.forgotPasswordLink}>
                    <a href="#" className={styles.link}>Olvidaste la contraseña?</a>
                  </div>
                </div>
                <div className={styles.inputWrapper}>
                  <Form.Control
                    type="password"
                    name="password"
                    id="password"
                    autoComplete="current-password"
                    required
                    className={styles.input}
                  />
                </div>
              </div>
              
              <div>
                <Button type="submit" className={styles.submitButton}>
                  Sign in
                </Button>
              </div>
            </Form>
            
            <p className={styles.notMember}>
              No tienes cuenta?
              <a href="#" className={styles.link}> Regístrate aquí</a>
            </p>
          </div>
        </div>
      </div>
    </div>
    </>
  );
}
